### ISSUE TITLE
build error happens on PG12.7

### ISSUE THREAD

**Issue by bigplaice** [apache/age#967]
**Describe the bug**
When build AGE 1.1.0-rc0 from source code, following build error happens:

[gpadmin@seg1 age-1.1.0-rc0]$ make PG_CONFIG=/home/gpadmin/AGE/pg12/install/bin/pg_config install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -O2 -fPIC -I.//src/include -I.//src/include/parser -I. -I./ -I/home/gpadmin/AGE/pg12/install/include/postgresql/server -I/home/gpadmin/AGE/pg12/install/include/postgresql/internal  -D_GNU_SOURCE   -c -o src/backend/age.o src/backend/age.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -O2 -fPIC -I.//src/include -I.//src/include/parser -I. -I./ -I/home/gpadmin/AGE/pg12/install/include/postgresql/server -I/home/gpadmin/AGE/pg12/install/include/postgresql/internal  -D_GNU_SOURCE   -c -o src/backend/catalog/ag_catalog.o src/backend/catalog/ag_catalog.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -O2 -fPIC -I.//src/include -I.//src/include/parser -I. -I./ -I/home/gpadmin/AGE/pg12/install/include/postgresql/server -I/home/gpadmin/AGE/pg12/install/include/postgresql/internal  -D_GNU_SOURCE   -c -o src/backend/catalog/ag_graph.o src/backend/catalog/ag_graph.c
src/backend/catalog/ag_graph.c: In function ‘insert_graph’:
src/backend/catalog/ag_graph.c:67:15: error: void value not ignored as it ought to be
     graph_oid = CatalogTupleInsert(ag_graph, tuple);
               ^
make: *** [<builtin>: src/backend/catalog/ag_graph.o] Error 1

// I think the same error would happen on other PG releases after PG12, like 13/14/15 as the function CatalogTupleInsert() returns void.

Thanks,
Steven

**Comment by bigplaice** [comment]
This is not a bug. I should use another code package for build on PG12.7
